name: Terraform Delete

on:
    workflow_dispatch:

jobs:
    create-resource:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Terraform init
          run: terraform init

        - name: Terraform destroy
          run: terraform destroy -auto-approve
          